version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pwd
      - ll
      - pip install -r requirements.txt
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'
  base-directory: revenue-analyzer