version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - sudo apt-get update -y
      - sudo apt install default-jre -y
      - sudo apt install scala -y
      - sudo apt install python3-pip -y
      - sudo apt install awscli -y
      - pip3 install -r requirements.txt
  build:
    commands:
      - python3 tests/TestTransformation.py
artifacts:
  files:
    - '**/*'